site_name: Scenario Templates
theme:
  name: material
  logo: ""

  features:
    #- navigation.tabs # uncomment this to make navigation on top
    - navigation.sections
    - toc.integrate
    - navigation.footer

nav:
- 'index.md'
- 'land.md'
- 'disastercommunication.md'
- 'gamification.md'
- 'evacuategame.md'
- 'evacuateresults.md'
- 'evacuatelatest.md'
- 'yourownevacuate.md'
- 'shelterchallenges.md'
- 'sheltergame.md'
- 'shelterresults.md'
- 'shelteradvice.md'
- 'yourownshelter.md'
- 'end.md'

extra:
  analytics:
    provider: google
    property: G-QHP6G2MPHB

markdown_extensions:
  - toc:
      toc_depth: 1
